#!/bin/zsh

xfce4-terminal -T "Bot Control" --working-directory=/home/rca/rcasoftware/s2015/bot_control/ \
--tab -T "Big" --working-directory=/home/rca/rcasoftware/s2015/season/big/ \
--tab -T "Little" --working-directory=/home/rca/rcasoftware/s2015/season/little/ \
--tab -T "Simulator" --working-directory=/home/rca/rcasoftware/s2015/simulator/src