#!/bin/zsh

xfce4-terminal -T "Bot Control" --working-directory=/home/rca/rcasoftware/s2013/bot_control/ \
--tab -T "Big" --working-directory=/home/rca/rcasoftware/s2013/season/big/projects/drive/ \
--tab -T "Little" --working-directory=/home/rca/rcasoftware/s2013/season/little/project/drive/ \
--tab -T "Simulator" --working-directory=/home/rca/rcasoftware/s2013/simulator/src