#!/bin/zsh

xfce4-terminal -T "Bot Control" --working-directory=/home/rca/rcasoftware/s2016/bot_control/ \
--tab -T "Big" --working-directory=/home/rca/rcasoftware/s2016/season/big/ \
--tab -T "Little" --working-directory=/home/rca/rcasoftware/s2016/season/little/ \
--tab -T "Simulator" --working-directory=/home/rca/rcasoftware/s2016/simulator/src